track_parcel:
  fields:
    trunkrs_nr:
      required: true
      example: "TR123456789"
      selector:
        text:
    postal_code:
      required: false
      example: "1234AB"
      selector:
        text:

untrack_parcel:
  fields:
    trunkrs_nr:
      required: true
      example: "TR123456789"
      selector:
        text:
